### ISSUE TITLE
Can't import Joomla

### ISSUE THREAD

**Issue by noxidsoft** [jekyll/jekyll-import#197]
I'm a newbie (coming from CMS) to Jekyll/prose testing, excited by it!

I run Macbook Pro, MAMP, compass/libsass, can confirm successfull install of gems (I already use bundler, etc).

Any help appreciated, I have attempted a Joomla database import via the following:

```
$ ruby -rubygems -e 'require "jekyll-import";
> JekyllImport::Importers::Joomla.run({
> "dbname" => "noxidso1_p2015",
> "user" => "admin",
> "password" => "********",
> "host" => "localhost",
> "section" => "1",
> "prefix" => "*****_"
> })'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require': LoadError: cannot load such file -- mysql (Sequel::AdapterNotFound)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/sequel-4.21.0/lib/sequel/adapters/mysql.rb:4:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/sequel-4.21.0/lib/sequel/adapters/mysql.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/sequel-4.21.0/lib/sequel/database/connecting.rb:97:in `load_adapter'
	from /Library/Ruby/Gems/2.0.0/gems/sequel-4.21.0/lib/sequel/database/connecting.rb:26:in `adapter_class'
	from /Library/Ruby/Gems/2.0.0/gems/sequel-4.21.0/lib/sequel/database/connecting.rb:55:in `connect'
	from /Library/Ruby/Gems/2.0.0/gems/sequel-4.21.0/lib/sequel/core.rb:95:in `connect'
	from /Library/Ruby/Gems/2.0.0/gems/sequel-4.21.0/lib/sequel/core.rb:374:in `adapter_method'
	from /Library/Ruby/Gems/2.0.0/gems/sequel-4.21.0/lib/sequel/core.rb:384:in `mysql'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-import-0.6.0/lib/jekyll-import/importers/joomla.rb:38:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-import-0.6.0/lib/jekyll-import/importer.rb:23:in `run'
	from -e:2:in `<main>'
$ 
```

**Comment by parkr** [comment]
Should it use mysql or mysql2? Just re-run with `-rmysql` or `-rmysql2` depending on this.

**Comment by parkr** [comment]
Looks like `mysql` needs to be added to this list: https://github.com/jekyll/jekyll-import/blob/master/lib/jekyll-import/importers/joomla.rb#L21-L28
