### ISSUE TITLE
CSV Importer 'build_name' undefined method 'split'

### ISSUE THREAD

**Issue by robertjuric** [jekyll/jekyll-import#236]
I'm not sure if its my environment, but I got an error when trying to run the CSV importer.

```text
/usr/local/rvm/gems/ruby-2.2.1/gems/jekyll-import-0.9.0/lib/jekyll-import/importers/csv.rb:42:in `build_name': undefined method `split' for nil:NilClass (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.2.1/gems/jekyll-import-0.9.0/lib/jekyll-import/importers/csv.rb:28:in `block in process'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1739:in `each'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1122:in `block in foreach'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1273:in `open'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1121:in `foreach'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/jekyll-import-0.9.0/lib/jekyll-import/importers/csv.rb:25:in `process'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/jekyll-import-0.9.0/lib/jekyll-import/importer.rb:23:in `run'
        from -e:2:in `<main>'
```

**Comment by parkr** [comment]
@robertjuric The CSV importer is looking for column 4 and column 4 doesn't exist. What does your CSV look like? Just the headers is fine.

**Comment by parkr** [comment]
See the docs here for more: http://import.jekyllrb.com/docs/csv/

**Comment by robertjuric** [comment]
My headers were:  
published_at, title, body, permalink, filter  
Though columns 4 and 5 were empty. My columns were not in the same order, probably the issue?

**Comment by parkr** [comment]
> My columns were not in the same order, probably the issue?

Yes, I believe that is the case.
