### ISSUE TITLE
Tumblr import error

### ISSUE THREAD

**Issue by alias1** [jekyll/jekyll-import#239]
```
⇒  jekyll import tumblr --url http://blog.devalias.net --format md --grab_images true --add_highlights true --rewrite_urls true -t
       Deprecation: The 'url' setting can only be set in your config files.
Fetching http://blog.devalias.net/api/read/json/?num=50&start=0
Page: 1 - Posts: 50
Fetching http://blog.devalias.net/api/read/json/?num=50&start=50
Page: 2 - Posts: 0
Configuration file: none

/Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-import-0.10.0/lib/jekyll-import/importers/tumblr.rb:211:in `block in rewrite_urls_and_redirects': uninitialized constant Jekyll::Post (NameError)
	from /Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-import-0.10.0/lib/jekyll-import/importers/tumblr.rb:206:in `map'
	from /Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-import-0.10.0/lib/jekyll-import/importers/tumblr.rb:206:in `rewrite_urls_and_redirects'
	from /Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-import-0.10.0/lib/jekyll-import/importers/tumblr.rb:61:in `process'
	from /Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-import-0.10.0/lib/jekyll-import/importer.rb:23:in `run'
	from /Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-import-0.10.0/lib/jekyll-import.rb:26:in `block (3 levels) in add_importer_commands'
	from /Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/devalias/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/bin/jekyll:13:in `<top (required)>'
	from /Users/devalias/.rbenv/versions/2.3.0/bin/jekyll:23:in `load'
	from /Users/devalias/.rbenv/versions/2.3.0/bin/jekyll:23:in `<main>'
```

**Comment by pathawks** [comment]
`uninitialized constant Jekyll::Post`

Looks like it will need to be updated to work with Jekyll 3

**Comment by alias1** [comment]
Any tips/guides on migrating it? Not really familiar with the code base, but if I have an idea of what needs doing can always give it a go.

Sent from Outlook Mobile




On Wed, Feb 10, 2016 at 9:13 AM -0800, "Pat Hawks" <notifications@github.com> wrote:












uninitialized constant Jekyll::Post



Looks like it will need to be updated to work with Jekyll 3

**Comment by alias1** [comment]
Workaround:

Gemfile
```
source 'https://rubygems.org'
gem 'jekyll','~>2.5.3'
gem 'jekyll-import'
```
`bundle install`
```
bundle exec jekyll import tumblr --url http://blog.devalias.net --format md --grab_images true --add_highlights true --rewrite_urls true -t
```
Then copy over the `_posts` and edit for Jekyll 3 as required.

**Comment by parkr** [comment]
That is unfortunate. It seems like it's only the importer using this old class and only when `--rewrite_urls` is `true`.
