### ISSUE TITLE
Error with tumblr import

### ISSUE THREAD

**Issue by mwweinberg** [jekyll/jekyll-import#354]
Apologies - I'm not familiar with ruby and don't know how to troubleshoot error messages.  I'm running this:
```
ruby -rubygems -e 'require "jekyll-import";
    JekyllImport::Importers::Tumblr.run({
      "url"            => "http://mweinbergblog.tumblr.com",
      "format"         => "html", # or "md"
      "grab_images"    => true,  # whether to download images as well.
      "add_highlights" => true,  # whether to wrap code blocks (indented 4 spaces) in a Liquid "highlight" tag
      "rewrite_urls"   => true   # whether to write pages that redirect from the old Tumblr paths to the new Jekyll paths
    })'
```

and getting this error message:

```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- jekyll-import (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```
I installed ruby just to run Jekyll so it should be a reasonably clean install.  Any help would be  most appreciated.

thanks

**Comment by mwweinberg** [comment]
Turns out I needed to install a library in ubuntu. If anyone else runs into this problem, this did the trick for me:
`sudo apt-get install zlib1g-dev`

**Comment by deyvedvm** [comment]
I had the same problem in Linux Mint 18

This tip above solved my problem
